"""updates

Revision ID: 541565fb8b4e
Revises: 6afaf784c304
Create Date: 2024-02-13 01:29:20.260390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '541565fb8b4e'
down_revision: Union[str, None] = '6afaf784c304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_types',
    sa.Column('currency_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('currency_type_name', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('currency_type_id'),
    sa.UniqueConstraint('currency_type_name')
    )
    op.create_index(op.f('ix_currency_types_currency_type_name'), 'currency_types', ['currency_type_name'], unique=False)
    op.create_table('transaction_statuses',
    sa.Column('status_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status_name', sa.String(length=63), nullable=False),
    sa.PrimaryKeyConstraint('status_id'),
    sa.UniqueConstraint('status_name')
    )
    op.create_index(op.f('ix_transaction_statuses_status_name'), 'transaction_statuses', ['status_name'], unique=False)
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('currency_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['currency_type_id'], ['currency_types.currency_type_id'], ),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('customer_name')
    )
    op.create_index(op.f('ix_customers_customer_name'), 'customers', ['customer_name'], unique=False)
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('currency_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['currency_type_id'], ['currency_types.currency_type_id'], ),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('product_name')
    )
    op.create_index(op.f('ix_products_product_name'), 'products', ['product_name'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('currency_type_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['currency_type_id'], ['currency_types.currency_type_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['transaction_statuses.status_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_index(op.f('ix_products_product_name'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_customers_customer_name'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_transaction_statuses_status_name'), table_name='transaction_statuses')
    op.drop_table('transaction_statuses')
    op.drop_index(op.f('ix_currency_types_currency_type_name'), table_name='currency_types')
    op.drop_table('currency_types')
    # ### end Alembic commands ###
